# serverless.yml for the aws-passthrough service

service: aws-passthrough

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AdministratorAccess

custom:

  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

functions:
  invoker:
    handler: handler.invoker
    name: invoker
    events:
      - http:
          path: invoker/get
          method: get
          cors: true

# CloudFormation resource templates
resources:

  # Cognito
    - ${file(resources/cognito-user-pool.yml)}
    - ${file(resources/cognito-identity-pool.yml)}

